services:
  application_programming_interfaces:
    container_name: "LLMRouterAPIs"
    build:
      context: ./
      dockerfile: Dockerfile
    command: python -m poetry run uvicorn app:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
